name: Build Electron App for Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t my-electron-app:windows -f Dockerfile.windows .
          docker run --rm my-electron-app:windows

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-windows
          path: |
            build/*.exe
            build/*.msi
