name: Build Electron App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for canvas
        run: sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

      - name: Install Node.js dependencies
        run: npm install

      - name: Build Electron App
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-linux
          path: |
            build/*.deb
            build/*.AppImage

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install MSYS2 for additional dependencies
        run: choco install msys2
        shell: cmd

      - name: Add MSYS2 to PATH
        run: |
          echo "C:\\tools\\msys64\\usr\\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\\tools\\msys64\\mingw64\\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell

      - name: Install GTK3 dependencies using MSYS2
        run: |
          C:\tools\msys64\usr\bin\bash -lc "pacman -Syu --noconfirm"
          C:\tools\msys64\usr\bin\bash -lc "pacman -S --noconfirm mingw-w64-x86_64-cairo mingw-w64-x86_64-pango mingw-w64-x86_64-gtk3"
        shell: cmd

      - name: Verify GTK installation
        run: |
          if (-Not (Test-Path -Path "C:\\tools\\msys64\\mingw64\\bin\\libcairo-2.dll")) { Write-Error "GTK installation failed"; exit 1 } else { Write-Output "GTK installation verified" }
        shell: powershell

      - name: Debug GTK installation
        run: |
          Get-ChildItem -Path "C:\\tools\\msys64\\mingw64\\bin"
        shell: powershell

      - name: Display PATH variable
        run: echo $Env:PATH
        shell: powershell

      - name: Install Node.js dependencies
        run: npm install

      - name: Build Electron App
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-windows
          path: |
            build/*.exe
            build/*.msi
